# -*- coding: utf-8 -*-
"""Csv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oj4M6vsJuqYgpiEKBzu7rxRQyUIsDFgq

Dev: fabiotbraga - Script desenvolvido para corrigir o arquivo csv
"""

import pandas as pd

df2 = pd.read_csv('/content/lista_de_produtos - lista_de_produtos.csv')
spec_chars = [","]
for char in spec_chars:
    df2['price'] = df2['price'].str.replace(char, '.')
    df2['description'] = df2['description'].str.replace(char, '.')
    df2['department'] = df2['department'].str.replace(char, '')

print(df2.to_string())



df2.to_csv('lista_produtos.csv', index=False)
df3 = pd.read_csv('lista_produtos.csv')
print(df3.to_string())